codecov:
  require_ci_to_pass: true
  precision: 2
  round: down
  layout: "reach, diff, flags, files"
  show_carryforward_flags: false
  allow_coverage_offsets: false

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70
        threshold: 5
    patch:
      default:
        target: 70
        threshold: 5
    changes:
      default:
        target: 80
        threshold: 5

ignore:
  - "tests"
  - "**/*.test.js"
  - "jest.setup.js"

comment:
  layout: "reach,diff,files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  show_carryforward_flags: false
  hide_project_coverage: false
  hide_branch_coverage: false

github:
  require_ci_to_pass: true
